name: Run Mac with VNC and LocalTunnel

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest

    steps:
      - name: Install XQuartz
        run: |
          brew install --cask xquartz

      - name: Install TigerVNC (Correct)
        run: |
          brew install tiger-vnc

      - name: Install Node.js
        run: |
          brew install node

      - name: Install LocalTunnel
        run: |
          npm install -g localtunnel

      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1280x720 -depth 24
          echo "VNC server started on display :1"

      - name: Expose VNC with LocalTunnel
        run: |
          lt --port 5901 --subdomain mymacvnc &
          sleep 5
          echo "Connect to your VNC at: https://mymacvnc.loca.lt"
