name: run-mac

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest
    steps:
      - name: Install XQuartz
        run: brew install --cask xquartz

      - name: Install TigerVNC
        run: brew install tiger-vnc

      - name: Add TigerVNC to PATH
        run: echo "/opt/homebrew/opt/tiger-vnc/bin" >> $GITHUB_PATH

      - name: Set VNC Password (PATH method)
        run: |
          mkdir -p ~/.vnc
          vncpasswd -f <<< "mypassword" > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC Server
        run: |
          vncserver :1
          sleep 5

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Expose VNC via LocalTunnel
        run: lt --port 5901 --subdomain mymacvnc
