name: iOS Simulator Cloud

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest
    steps:
      - name: Install Dependencies
        run: |
          brew install tiger-vnc node
          npm install -g localtunnel
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Start iOS Simulator
        run: |
          open -a Simulator
          sleep 20

      - name: Start VNC + noVNC
        run: |
          /opt/homebrew/bin/vncserver :1 -geometry 1280x720 -depth 24
          nohup ~/noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 8080 &

      - name: Start LocalTunnel
        run: |
          lt --port 8080 --subdomain ioscloudsim &
          sleep 5
          echo "===================================="
          echo "iOS Simulator public URL below:"
          echo "https://ioscloudsim.loca.lt/vnc.html"
          echo "===================================="

      - name: Keep Alive
        run: |
          sleep 21600
