name: iOS Simulator Cloud

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest
    steps:
      - name: Install noVNC
        run: |
          brew install tigervnc
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify

      - name: Start iOS Simulator
        run: |
          open -a Simulator
          sleep 20

      - name: Start VNC Server
        run: |
          vncserver -localhost no :1
          export DISPLAY=:1
          nohup ~/noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 8080 &

      - name: Keep Alive
        run: |
          echo "Simulator running... Press Ctrl+C to stop."
          sleep 21600 # 6 hours
