name: iOS + LocalTunnel Workflow

on:
  workflow_dispatch:

jobs:
  ios-emulator:
    name: Run iOS Simulator
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install --cask xquartz

      - name: Start iOS Simulator
        run: |
          echo "Starting iOS Simulator..."
          xcrun simctl list
          xcrun simctl boot "iPhone 14"
          xcrun simctl bootstatus "iPhone 14"
          open -a Simulator

  localtunnel:
    name: Start LocalTunnel
    runs-on: ubuntu-latest
    needs: ios-emulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Start simple HTTP server (background)
        run: |
          nohup python3 -m http.server 8000 &
          sleep 3

      - name: Start LocalTunnel
        run: |
          lt --port 8000 --subdomain mera-test &
          sleep 5

      - name: Show tunnel link
        run: echo "Public link ready: https://mera-test.loca.lt"
