name: Run Mac with VNC and LocalTunnel

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest

    steps:
      - name: Install XQuartz
        run: brew install --cask xquartz

      - name: Install TigerVNC
        run: brew install tiger-vnc

      - name: Install Node.js and LocalTunnel
        run: |
          brew install node
          npm install -g localtunnel

      - name: Add TigerVNC to PATH
        run: echo "/opt/homebrew/opt/tiger-vnc/bin" >> $GITHUB_PATH

      - name: Set VNC Password
        run: |
          mkdir -p ~/.vnc
          echo "mypassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC Server
        run: vncserver :1 -geometry 1280x720 -depth 24

      - name: Expose with LocalTunnel
        run: lt --port 5901 --subdomain mymacvnc
