name: Run iOS Simulator on Mac

on:
  workflow_dispatch:

jobs:
  run-mac:
    runs-on: macos-latest
    steps:
      - name: Install Homebrew packages
        run: |
          brew install --cask xquartz
          brew install tigervnc
          brew install --cask novnc

      - name: Install Node + LocalTunnel
        run: |
          brew install node
          npm install -g localtunnel

      - name: Start VNC Server
        run: |
          export PATH="$(brew --prefix)/bin:$PATH"
          tigervncserver -geometry 1280x800

      - name: Start noVNC
        run: |
          /Applications/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 8080 &

      - name: Start LocalTunnel
        run: |
          lt --port 8080 --subdomain ios-sim-test > lt_url.txt &
          sleep 5
          cat lt_url.txt

      - name: Boot iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14"
          xcrun simctl bootstatus "iPhone 14" -b
          echo "iOS Simulator Ready!"
