name: LocalTunnel Server

on:
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js install karo
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: LocalTunnel install karo
        run: npm install -g localtunnel

      - name: Server run karo (background mein)
        run: |
          nohup python3 -m http.server 8000 &
          sleep 3

      - name: LocalTunnel start karo
        run: |
          lt --port 8000 --subdomain mera-test &
          sleep 5

      - name: Show tunnel link
        run: echo "Public link ready: https://mera-test.loca.lt"
